### ISSUE TITLE
Add hippo feeding mechanic

### ISSUE THREAD

**Issue by randomPoison** [excaliburHisSheath/hangry-river-horse#35]
Currently, the player gets 1 point for every 1 tap on the screen, and each tap causes the hippo to do its "chomp" animation. Instead, let's build a 2 step hippo feeding process:

* For each tap on the screen, the player places a colorful ball in a pile in front of their hippo.
* At a determined rate, the hippo automatically eats the balls in the pile in front of it. For each ball the hippo eats, the player gets a point.

Some notes:

* There should be an animation on the host display of a ball dropping into the pile when the player taps their screen.
* Balls should be given a random color according to the color theme.
* The hippo chomp animation should happen when the hippo eats, rather than when the player taps.
* The hippos chomp should get faster over time, going to a max of maybe 5 comps/sec (roughly as fast as a player can tap).
* When a hippo tries to eat but has no balls left, it should leave the screen and the player is removed from the backend (maybe after a short grace period).

**Comment by wufire** [comment]
Maybe we could implement this as a 'strike' system. Every chomp with no food earns the hippo a strike. At a certain number of strikes, the hippo is removed.

Alternately, if we consider hippo chomp speed as a 'difficulty level' that increases as the hippo eats, a strike could instead be a 'level down' until eventually, at the easiest level, the hippo is removed.

**Comment by randomPoison** [comment]
I like the version where the hippo's chomp speed gradually drops until they're removed, since that feels like it penalizes the player for not feeding their hippo (since they aren't gaining points as fast).

**Comment by randomPoison** [comment]
I never finished implementing the variable chomp speed, but we're not going to go farther with this mechanic anyway.
